# Generated by Django 4.0.2 on 2022-02-10 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.JSONField(verbose_name='Описание')),
                ('preview_image', models.ImageField(upload_to='uploads/previews/', verbose_name='Preview')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customers_num', models.IntegerField(default=-1, verbose_name='Максимальное количество посетителей')),
                ('can_customers_speak', models.BooleanField(default=True, verbose_name='Могут ли клиенты говорить')),
                ('show_customers_video', models.BooleanField(default=True, verbose_name='Показывать видео клиентов')),
                ('do_loud_voice', models.BooleanField(default=True, verbose_name='Слышно ли создателя везде')),
                ('slug', models.SlugField(max_length=150)),
                ('black_list', models.ManyToManyField(related_name='black_list', to=settings.AUTH_USER_MODEL, verbose_name='Чёрный список')),
                ('customers', models.ManyToManyField(related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='Посетители')),
                ('room_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.roomimage', verbose_name='Образ комнаты')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('password', models.CharField(default=None, max_length=150, null=True, verbose_name='Ключ доступа')),
                ('slug', models.SlugField(max_length=150)),
                ('owners', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('rooms', models.ManyToManyField(to='meetings.Room', verbose_name='Комнаты')),
            ],
        ),
    ]
