# Generated by Django 4.0.2 on 2022-07-24 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.JSONField(verbose_name='Описание')),
                ('preview_image', models.ImageField(upload_to='uploads/previews/', verbose_name='Preview')),
            ],
            options={
                'verbose_name': 'Образ комнаты',
                'verbose_name_plural': 'Образы комнаты',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('can_customers_speak', models.BooleanField(default=True, verbose_name='Могут ли клиенты говорить')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('room_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.roomimage', verbose_name='Образ комнаты')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('password', models.CharField(default=None, max_length=150, null=True, verbose_name='Ключ доступа')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('black_list', models.ManyToManyField(blank=True, related_name='black_list', to=settings.AUTH_USER_MODEL, verbose_name='Чёрный список')),
                ('customers', models.ManyToManyField(blank=True, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='Посетители')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master', to=settings.AUTH_USER_MODEL, verbose_name='Хозяин')),
                ('owners', models.ManyToManyField(related_name='owners', to=settings.AUTH_USER_MODEL, verbose_name='Создатели')),
                ('rooms', models.ManyToManyField(to='meetings.Room', verbose_name='Комнаты')),
            ],
            options={
                'verbose_name': 'Встреча',
                'verbose_name_plural': 'Встречи',
            },
        ),
    ]
