# Generated by Django 4.0.2 on 2022-02-19 09:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'verbose_name': 'Встреча', 'verbose_name_plural': 'Встречи'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Комната', 'verbose_name_plural': 'Комнаты'},
        ),
        migrations.AlterModelOptions(
            name='roomimage',
            options={'verbose_name': 'Образ комнаты', 'verbose_name_plural': 'Образы комнаты'},
        ),
        migrations.RemoveField(
            model_name='room',
            name='customers',
        ),
        migrations.RemoveField(
            model_name='room',
            name='customers_num',
        ),
        migrations.AddField(
            model_name='meeting',
            name='customers',
            field=models.ManyToManyField(blank=True, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='Посетители'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='owners',
            field=models.ManyToManyField(related_name='owners', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='black_list',
            field=models.ManyToManyField(blank=True, related_name='black_list', to=settings.AUTH_USER_MODEL, verbose_name='Чёрный список'),
        ),
        migrations.AlterField(
            model_name='room',
            name='show_customers_video',
            field=models.BooleanField(default=True, verbose_name='Показывать видео участников'),
        ),
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
