# Generated by Django 4.0.2 on 2022-02-19 10:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0002_alter_meeting_options_alter_room_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='black_list',
        ),
        migrations.AddField(
            model_name='meeting',
            name='black_list',
            field=models.ManyToManyField(blank=True, related_name='black_list', to=settings.AUTH_USER_MODEL, verbose_name='Чёрный список'),
        ),
    ]
