# Generated by Django 4.0.2 on 2022-02-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_remove_room_black_list_meeting_black_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='test room', max_length=150),
            preserve_default=False,
        ),
    ]
