# Generated by Django 4.0.2 on 2022-03-09 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='do_loud_voice',
        ),
        migrations.RemoveField(
            model_name='room',
            name='show_customers_video',
        ),
    ]
